services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: freesoldier
      MYSQL_PASSWORD: AdMaTai2020
      MYSQL_ROOT_PASSWORD: AdMaTai2020
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/base
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://freesoldier:AdMaTai2020@db/mydb
    depends_on:
      - db

volumes:
  mysql_data:
