app:
  name: "hamadrich-app"
  labels:
    app: "web-app"
  replicas: 2
  image: "manofer/hamadrich-lamishtachrer:0.1"
  containerPort: 5000
  env:
    FLASK_APP: "run.py"
    FLASK_ENV: "development"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  initContainer:
    name: "wait-for-database"
    image: "busybox:1.28"
    command: "until nc -z -v -w30 {{ .Values.database.service }} {{ .Values.database.port }}; do echo 'waiting for database'; sleep 5; done"

db:
  name: mydb

credentials:
  root:
    user: root
    password: "AdMaTai2020"

serviceApp:
  name: "hamadrich-app-service"
  port: 80
  targetPort: 5000
  type: "ClusterIP"

ingress:
  name: "hamadrich-ingress"
  annotations:
    ingressClass: "nginx"
  rules:
    appHost: "hamadrich-lamishtachrer.com"
    jenkinsHost: "hamadrich-Jenkins.com"
    path: "/"
    pathType: "Prefix"
    backend:
      appServiceName: "hamadrich-app-service"
      jenkinsServiceName: "jenkins"
      appServicePort: 80
      jenkinsServicePort: 8080

metallb:
  ipAddressPool:
    name: "example"
    namespace: "metallb-system"
    addresses:
      - "172.18.255.200-172.18.255.250"
  l2Advertisement:
    name: "empty"
    namespace: "metallb-system"
