apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.app.name } }
  labels:
    app: { { .Values.app.labels.app } }
spec:
  replicas: { { .Values.app.replicas } }
  selector:
    matchLabels:
      app: { { .Values.app.labels.app } }
  template:
    metadata:
      labels:
        app: { { .Values.app.labels.app } }
    spec:
      initContainers:
        - name: { { .Values.app.initContainer.name } }
          image: { { .Values.app.initContainer.image } }
          command: ["sh", "-c", "{{ .Values.app.initContainer.command }}"]
      containers:
        - name: { { .Values.app.name } }
          image: { { .Values.app.image } }
          ports:
            - containerPort: { { .Values.app.containerPort } }
          env:
            - name: FLASK_APP
              value: { { .Values.app.env.FLASK_APP } }
            - name: FLASK_ENV
              value: { { .Values.app.env.FLASK_ENV } }
            - name: DATABASE_URL
              value: { { .Values.app.env.DATABASE_URL } }
          resources:
            requests:
              memory: { { .Values.app.resources.requests.memory } }
              cpu: { { .Values.app.resources.requests.cpu } }
            limits:
              memory: { { .Values.app.resources.limits.memory } }
              cpu: { { .Values.app.resources.limits.cpu } }
