apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hamadrich-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: hamadrich-lamishtachrer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hamadrich-app-service
                port:
                  number: 80
