apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service-db.name } }
  labels:
    app: { { .Values.database.labels.app } }
spec:
  ports:
    - port: { { .Values.service-db.port } }
      name: { { .Values.service-db.portName } }
  clusterIP: { { .Values.service-db.clusterIP } }
  selector:
    app: { { .Values.database.labels.app } }
