apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service-app.name } }
  labels:
    app: { { .Values.app.labels.app } }
spec:
  selector:
    app: { { .Values.app.labels.app } }
  ports:
    - protocol: { { .Values.service-app.protocol } }
      port: { { .Values.service-app.port } }
      targetPort: { { .Values.service-app.targetPort } }
  type: { { .Values.service-app.type } }
