apiVersion: v1
kind: Service
metadata:
  name: hamadrich-database-service
  labels:
    app: database
spec:
  ports:
    - port: 3306
      name: http
  clusterIP: None
  selector:
    app: database
