apiVersion: v1
kind: Service
metadata:
  name: hamadrich-app-service
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
