apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceApp.name }}
  labels:
    app: {{ .Values.app.labels.app }}
spec:
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    - protocol: {{ .Values.serviceApp.protocol }}
      port: {{ .Values.serviceApp.port }}
      targetPort: {{ .Values.serviceApp.targetPort }}
  type: {{ .Values.serviceApp.type }}

