apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hamadrich-database
  labels:
    app: database
spec:
  serviceName: hamadrich-database-service
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_USER
              value: freesoldier
            - name: MYSQL_PASSWORD
              value: AdMaTai2020
            - name: MYSQL_ROOT_PASSWORD
              value: AdMaTai2020
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
